//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUSSAN_TUNQUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercaderia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mercaderia()
        {
            this.Registro = new HashSet<Registro>();
        }
    
        public int idMercaderia { get; set; }
        public string descripcionMercaderia { get; set; }
        public Nullable<decimal> areaCubica { get; set; }
        public int idCliente { get; set; }
        public int idTipoMerca { get; set; }
        public string categoria { get; set; }
        public string unidad { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro> Registro { get; set; }
        public virtual TipoMercaderia TipoMercaderia { get; set; }
    }
}
