//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUSSAN_TUNQUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int idRegistro { get; set; }
        public int idCliente { get; set; }
        public int idMercaderia { get; set; }
        public int idTipoRegistro { get; set; }
        public int idEmpleado { get; set; }
        public string fecha { get; set; }
        public int cantidad { get; set; }
        public decimal areaCubica { get; set; }
        public int estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Mercaderia Mercaderia { get; set; }
        public virtual TipoRegistro TipoRegistro { get; set; }
    }
}
